<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <PackageId>OreSoftware.Flags2Env</PackageId>
    <Version>0.1.0</Version>
    <Authors>ORESoftware</Authors>
    <Description>C# bindings for flags2env.</Description>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <PackageProjectUrl>https://github.com/ORESoftware/flags-2-env</PackageProjectUrl>
    <RepositoryUrl>https://github.com/ORESoftware/flags-2-env</RepositoryUrl>
    <GeneratePackageOnBuild>false</GeneratePackageOnBuild>
    <Nullable>enable</Nullable>
    <LangVersion>latest</LangVersion>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="System.Text.Json" Version="8.0.5" />
    <Compile Remove="Flags2EnvTest.cs" />
    <None Include="native/parser.c" Pack="true" PackagePath="native/" />
    <None Include="native/parser.h" Pack="true" PackagePath="native/" />
  </ItemGroup>
</Project>
