name = "flags2env"
version = "0.1.0"
license = "MIT"
author = "ORESoftware"
maintainer = "ORESoftware"
copyright = "Copyright ORESoftware"

[library]
source-dir = "src"

[[test]]
name = "smoke"
source-dir = "."
main = "test.f90"
