configPath = fullfile(tempdir, "flags2env-matlab-smoke.toml");
fid = fopen(configPath, "w");
fprintf(fid, "%s\n", ...
    "[flags.port]", ...
    "env = ""PORT""", ...
    "aliases = [""port""]", ...
    "type = ""integer""", ...
    "", ...
    "[flags.debug]", ...
    "env = ""DEBUG""", ...
    "aliases = [""debug""]", ...
    "type = ""bool""", ...
    "true_aliases = [""t""]");
fclose(fid);

env = flags2env.parse(["app", "--debug=t", "--port", "8181"], configPath);
assert(strcmp(env.DEBUG, "true"));
assert(strcmp(env.PORT, "8181"));
